# This is a basic workflow to help you get started with Actions


name: SpaceX Project CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/spacex
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [4.4]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
      - name: MongoDB for github actions
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.7.0
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
